version: '2'
services:
  del-mysql:
    image: mysql:5.7.27
    # volumes:
    #     - ~/volumes/jhipster/del/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=root
      #      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=delmoney329
      - MYSQL_DATABASE=del
    ports:
      - 3308:3306
    #    expose:
    #      - 3308
    volumes:
      - /usr/local/jhipster/del/mysql/data:/var/lib/mysql # 挂载数据目录
      - /usr/local/jhipster/del/my.cnf:/etc/mysql # 挂载配置文件目录
      - /usr/local/jhipster/del/mydir:/mydir
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
